# Generated by Django 3.0.5 on 2020-04-20 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vendor_code',
        ),
    ]
