# Generated by Django 3.0.5 on 2020-04-21 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_order_isactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
