# Generated by Django 3.0.5 on 2020-04-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='id_number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
