# Generated by Django 3.0.5 on 2020-04-21 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
    ]
